/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalfuzzy.Vista;

import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import proyectofinalfuzzy.Controlador.ParametrosGeneralesController;

/**
 *
 * @author Tatiana Astudillo
 */
public class FrmListadoParametrosGenerales extends javax.swing.JFrame {

    ParametrosGeneralesController pgc = new ParametrosGeneralesController();

    /**
     * Creates new form FrmListadoParametrosGenerales
     */
    public FrmListadoParametrosGenerales() {
        //crearPanelRojoPrueba();
        //pgc.mostrarInformacionEnPaneles(this);
        crearPanelesDesdeLista(pgc.mostrarInformacionEnPaneles());
        //crearPanelesDesdeLista(Arrays.asList("Prueba1", "Prueba2", "Prueba3", "Prueba4", "Prueba5", "Prueba6"));
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INVERAGRO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 434, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListadoParametrosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListadoParametrosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListadoParametrosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListadoParametrosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListadoParametrosGenerales().setVisible(true);
            }
        });
    }

    public void crearPanelesDesdeLista(List<String> palabras) {

        int x = 50; // Coordenada x inicial
        int y = 100; // Coordenada y fija (puedes ajustarla según sea necesario)
        int panelesEnFila = 0;
        for (String palabra : palabras) {
            JPanel panel = crearPanelConPalabra(palabra);
            panel.setBounds(x, y, 200, 100); // Ajusta las dimensiones según tus necesidades
            this.add(panel);
            panelesEnFila++;
            if (panelesEnFila == 3) {
                // Si se alcanza el límite de tres paneles, reinicia la coordenada x y aumenta la coordenada y
                x = 50; // Coordenada x inicial
                y += 120; // Ajusta el espacio vertical entre filas según sea necesario
                panelesEnFila = 0;
            } else {
              x += 210; // Ajusta el espacio horizontal entre paneles según sea necesario
            }
        }
        this.revalidate();
        this.repaint();
    }

    private JPanel crearPanelConPalabra(String linea) {
        JPanel panel = new JPanel();
        panel.setBackground(Color.RED);

        //JLabel etiqueta = new JLabel(linea);
        JLabel etiqueta;
        String[] partes = linea.split(",");
        for (String parte : partes) {
            etiqueta = new JLabel(parte);
            etiqueta.setForeground(Color.WHITE);
            panel.add(etiqueta);
        }
        return panel;
    }

//    public void crearPanelRojoPrueba() {
//        JPanel panel = new JPanel();
//        panel.setBackground(Color.RED);
//
//        JLabel etiqueta = new JLabel("Prueba");
//        etiqueta.setForeground(Color.WHITE); // Para que el texto sea visible en el fondo rojo
//        panel.add(etiqueta);
//        setLayout(null);
//        //1 left,bootom, ancho, largo
//        panel.setBounds(50, 100, 200, 100); // ajusta las coordenadas y dimensiones según tus necesidades
//
//        this.add(panel);
//        this.setVisible(true);
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
